### ISSUE TITLE
Error: inherits(x, "character") is not TRUE      UDpipe

### ISSUE THREAD

**Issue by touseefshoonya** [amrrs/text-analysis-with-udpipe#1]
Hi,
Problem statement:The issue is coming when when i am using the first function of udpipe "udpipe_annotate()"
Issue:  Error: inherits(x, "character") is not TRUE.

I have even copy pasted your code to see if i am doing something wrong while writing the code or not?

Code:

#setwd("E:/Data science")
#install.packages("udpipe")
require(dplyr)
require(ggplot2)
news <- read.csv(choose.files())
news %>% group_by(publish_date) %>% count() %>% arrange(desc(n))
#plotting to unsderstand the how the frequency of headlines is:

news %>% group_by(publish_date) %>% count() %>% ggplot() + geom_line(aes(publish_date,n, group = 1))

#split year month and date

#install.packages("stringr")
require(stringr)
news_more <- news %>% mutate(year = str_sub(publish_date,1,4),
                             month = str_sub(publish_date,5,6),
                             date = str_sub(publish_date,7,8))#lets see distribution of data based on year

news_more %>% group_by(year) %>% count()  %>% ggplot() + geom_bar(aes(year,n), stat ='identity')

#Using pre trained language models for of udpipe
require(udpipe)

#model <- udpipe_download_model(language = "english")
udmodel_english <- udpipe_load_model(file = 'english-ud-2.0-170801.udpipe')

#Filtering data only for 2008

news_more_2008 <- news_more %>% filter(year == 2008 & month == 10)

#first function that we’d use in udpipe to get started with our Text Analysis journey

s <- udpipe_annotate(udmodel_english, news_more_2008$headline_text)

Thanks,
Touseef

**Comment by amrrs** [comment]
Thanks @touseefshoonya for checking the code, i think when you read the input data the characters could've been read as Factors. Try `str(news)` and see the result.

**Comment by shashankgjoshi** [comment]
Did this get resolved? I am getting the same error for the same example. I tried 

s <- udpipe_annotate(udmodel_english, str(news_more_2008$headline_text))

and getting the following message

Factor w/ 1076225 levels "'a bump in the road': economic results a wake up call; pm says",..: 6143 8033 8475 11916 9379 17255 17353 19336 23051 23122 ...
Error in udpipe_annotate(udmodel_english, str(news_more_2008$headline_text)) : 
  inherits(x, "character") is not TRUE

**Comment by amrrs** [comment]
Hi @shashankgjoshi Did you read the input csv as characters (not factors) ?

Can you display the data types using `str()`

**Comment by shashankgjoshi** [comment]
I just checked. I gave the command str(news$headline_text). It shows it as Factor.  Following is the output.

Factor w/ 1076225 levels "'a bump in the road': economic results a wake up call; pm says",..: 11762 20164 9853 32509 32513 42247 56311 72142 74110 77416 ...

**Comment by amrrs** [comment]
That's the issue. use this to convert it to character and try!

`news$headline_text <- as.character(news$headline_text)`

**Comment by shashankgjoshi** [comment]
Yes. It worked. Understood. Thanks a lot.

**Comment by amrrs** [comment]
You're welcome!
