### ISSUE TITLE
Rake and noun phrases

### ISSUE THREAD

**Issue by achintyaakumar** [amrrs/text-analysis-with-udpipe#3]
The keywords identified by RAKE and the noun phrases end up being single words for me when I've been trying to get entities. I don't know why that is happening. One thing I did differently is that I used the file model instead of the english-ud-2.0 because I got the following error: 
Error in udpipe_load_model(file = "english-ud-2.0-170801.udpipe") : 
  File english-ud-2.0-170801.udpipe containing the language model does not exist
Any ideas as to how I can fix this?

**Comment by pawar30** [comment]
@achintyaakumar , you will have to download the current English language model (line 71 in the .Rmd file. It is commented). I believe the latest version is english-ewt-ud-2.4-190531.udpipe. You will have to make this change as well when you load the model. Should work fine with these changes.

**Comment by amrrs** [comment]
I'm so sorry couldn't respond. Thanks @pawar30 for the response!
